# Generated by Django 5.1.3 on 2024-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_alter_drivers_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date_time', models.DateTimeField()),
                ('action', models.CharField(choices=[('Изменение задержки светофора', 'DURATION_CHANGE'), ('Заупск мигающего режима', 'ACCIDENT_MODE'), ('Другое', 'OTHER')], max_length=100)),
                ('actor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('traffic_value', models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR'), ('5', 'FIVE'), ('6', 'SIX'), ('7', 'SEVEN'), ('8', 'EIGHT'), ('9', 'NINE'), ('10', 'TEN')], default='1', max_length=20)),
                ('dot', models.CharField(max_length=100)),
                ('traffic_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
    ]
