# Generated by Django 5.1.3 on 2024-12-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_log_streets_delete_drivers_delete_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streets',
            name='dot',
        ),
        migrations.RemoveField(
            model_name='streets',
            name='traffic_time',
        ),
        migrations.AddField(
            model_name='streets',
            name='time_end',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='streets',
            name='time_start',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='streets',
            name='name',
            field=models.CharField(default='Красная', max_length=100),
        ),
    ]
