# Generated by Django 5.1.3 on 2024-12-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_remove_streets_dot_remove_streets_traffic_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streets',
            name='traffic_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
