# Generated by Django 5.1.4 on 2024-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_streets_traffic_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streets',
            name='time_end',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
