# Generated by Django 5.1.3 on 2024-12-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_alter_streets_time_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='actor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='log',
            name='action',
        ),
        migrations.RemoveField(
            model_name='log',
            name='log_date_time',
        ),
        migrations.AddField(
            model_name='log',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
