# Generated by Django 5.1.3 on 2024-12-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_rename_actor_log_user_remove_log_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='username',
        ),
    ]
