# Generated by Django 5.1.3 on 2024-12-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_rename_user_log_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='username',
            new_name='questor',
        ),
    ]
